### ISSUE TITLE
AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/]')

### ISSUE THREAD

**Issue by ghost** [jstakun/elastalert-ocp#4]
Hi Jaroslaw

Thank you for this project, I am trying to deploy elastalert to my RedHat Openshift and to make it work with our elasticsearch service in service-telemetry framework.

Once deployed, mailman and elastalert pods are up and running, but when I see the logs of elastalert pod I see below ERRORs even I have es_username and es_password configured in elastalert-ocp.yaml file, config.yaml cm section for elastalert:

```
$ oc get pods
NAME                      READY   STATUS      RESTARTS   AGE
elastalert-ocp-1-deploy   0/1     Completed   0          39m
elastalert-ocp-1-m8fh2    1/1     Running     0          39m
mailman-1-62x92           1/1     Running     0          39m
mailman-1-deploy          0/1     Completed   0          39m

$ os logs elastalert-ocp-1-m8fh2
Checking Elastic Version
Elastic Version: 7.10.2
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation.
1 rules loaded
WARNING:elasticsearch:GET https://elasticsearch-es-http.service-telemetry.svc:9200/ [status:401 request:0.030s]
WARNING:elasticsearch:GET https://elasticsearch-es-http.service-telemetry.svc:9200/ [status:401 request:0.004s]
WARNING:elasticsearch:GET https://elasticsearch-es-http.service-telemetry.svc:9200/ [status:401 request:0.004s]
WARNING:elastalert:Error connecting to Elasticsearch for rule VAN3 ERROR User Alert. The rule has been disabled.
ERROR:root:Error connecting to SMTP host: [Errno 111] Connection refused
WARNING:elasticsearch:GET https://elasticsearch-es-http.service-telemetry.svc:9200/ [status:401 request:0.019s]
WARNING:elasticsearch:GET https://elasticsearch-es-http.service-telemetry.svc:9200/ [status:401 request:0.004s]
WARNING:elasticsearch:GET https://elasticsearch-es-http.service-telemetry.svc:9200/ [status:401 request:0.004s]
ERROR:root:Error writing alert info to Elasticsearch: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/]')
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 975, in init_rule
    self.modify_rule_for_ES5(new_rule)
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1047, in modify_rule_for_ES5
    if rule_es.is_atleastfive():
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/__init__.py", line 62, in is_atleastfive
    return int(self.es_version.split(".")[0]) >= 5
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/__init__.py", line 50, in es_version
    self._es_version = self.info()['version']['number']
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/client/__init__.py", line 287, in info
    "GET", "/", params=params, headers=headers
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/connection/http_requests.py", line 199, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/connection/base.py", line 316, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1981, in send_notification_email
    smtp = SMTP(self.smtp_host)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1614, in writeback
    index = self.writeback_es.resolve_writeback_index(self.writeback_index, doc_type)
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/__init__.py", line 94, in resolve_writeback_index
    if not self.is_atleastsix():
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/__init__.py", line 68, in is_atleastsix
    return int(self.es_version.split(".")[0]) >= 6
  File "/opt/app-root/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/__init__.py", line 50, in es_version
    self._es_version = self.info()['version']['number']
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/client/__init__.py", line 287, in info
    "GET", "/", params=params, headers=headers
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/connection/http_requests.py", line 199, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch-7.10.1-py3.6.egg/elasticsearch/connection/base.py", line 316, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/]')
```

So my question is what is the correct way to provide http_auth credentials to elastalert when deploying to openshift using your project and prevent this issue?

This is my elastalert-ocp.yaml file version to deploy elastalert to Openshift:

```apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: elastalert-ocp
    name: elastalert-ocp
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: elastalert-ocp
      deploymentconfig: elastalert-ocp
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: elastalert-ocp
          deploymentconfig: elastalert-ocp
      spec:
        containers:
        - image: quay.io/jstakun/elastalert-ocp:v0.2.4
          imagePullPolicy: IfNotPresent
          name: elastalert-ocp
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/elastalert/config
            name: config
          - mountPath: /opt/elastalert/rules
            name: rules
          - mountPath: /etc/es/keys
            name: elasticsearch-es-cert
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: config-cm
          name: config
        - configMap:
            defaultMode: 420
            name: rules-alerting
          name: rules
        - name: elasticsearch-es-cert
          secret:
            defaultMode: 420
            secretName: elasticsearch-es-cert
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - elastalert-ocp
        from:
          kind: ImageStreamTag
          name: elastalert-ocp:v0.2.4
          namespace: openshift-elastalert
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: mailman
    name: mailman
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: mailman
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: mailman
      spec:
        containers:
        - env:
          - name: PORT
            value: "10025"
          image: quay.io/jstakun/fake-smtp:latest
          imagePullPolicy: IfNotPresent
          name: mailman
          ports:
          - containerPort: 10025
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/mail
            name: mailman-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: mailman-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mailman
        from:
          kind: ImageStreamTag
          name: mailman:latest
          namespace: openshift-elastalert
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: elastalert-ocp
    name: elastalert-ocp
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: elastalert-ocp
      deploymentconfig: elastalert-ocp
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: mailman
    name: mailman
  spec:
    ports:
    - name: 10025-tcp
      port: 10025
      protocol: TCP
      targetPort: 10025
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: mailman
    sessionAffinity: None
    type: ClusterIP
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: elastalert-ocp
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/jstakun/elastalert-ocp
      generation: 5
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/jstakun/elastalert-ocp:v0.1.39
      generation: 4
      importPolicy: {}
      name: v0.1.39
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/jstakun/elastalert-ocp:v0.2.1
      generation: 6
      importPolicy: {}
      name: v0.2.1
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/jstakun/elastalert-ocp:v0.2.4
      generation: 7
      importPolicy: {}
      name: v0.2.4
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: mailman
    name: mailman
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: quay.io/jstakun/fake-smtp:latest
      from:
        kind: DockerImage
        name: quay.io/jstakun/fake-smtp:latest
      generation: 3
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  data:
    config.yaml: |
      #This is the folder that contains the rule yaml files
      # Any .yaml file will be loaded as a rule
      rules_folder: rules

      scan_subdirectories: false

      # How often ElastAlert will query elasticsearch
      # The unit can be anything from weeks to seconds
      run_every:
        minutes: 1

      # ElastAlert will buffer results from the most recent
      # period of time, in case some log sources are not in real time
      buffer_time:
        minutes: 15

      # The elasticsearch service for metadata writeback
      # Note that every rule can have it's own elasticsearch host
      es_host: elasticsearch-es-http.service-telemetry.svc
      es_username: "elastic"
      es_password: "passwordgoeshere"

      # The elasticsearch port
      es_port: 9200

      # The index on es_host which is used for metadata storage
      # This can be a unmapped index, but it is recommended that you run
      # elastalert-create-index to set a mapping
      writeback_index: elastalert_status

      # If an alert fails for some reason, ElastAlert will retry
      # sending the alert until this time period has elapsed
      alert_time_limit:
        days: 2

      use_ssl: True
      verify_certs: True

      # The secrets from the curator must be mounted!
      ca_certs: /etc/es/keys/ca.crt
      client_cert: /etc/es/keys/tls.crt
      client_key: /etc/es/keys/tls.key

      # paste here value of command: 'oc sa get-token elastalert'
      es_bearer: 

      # smpt settings
      email: 'fortistack_admin@fortinet.com'
      smpt_host: 'mailman'
      smtp_port: 10025
      from_addr: 'elastalert@fortinet.com'
  kind: ConfigMap
  metadata:
    name: config-cm
- apiVersion: v1
  data:
    my-rules.yaml: |
      name: ERROR User Alert
      type: frequency
      index: van3*
      num_events: 1

      timeframe:
          minutes: 1

      filter:
      - query:
          query_string:
            query: "message:*ERROR*"

      #SMTP
      smtp_host: 'mailman'
      smtp_port: 10025
      #
      from_addr: 'elastalert@localhost'
      #
      ## (Required)
      ## The alert is use when a match is found
      alert:
      - "email"
      #
      email:
      - "admin@localhost"
      #
  kind: ConfigMap
  metadata:
    name: rules-alerting
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: elastalert
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

I would be appreciated if you can point what to check next, thank you!

**Comment by jstakun** [comment]
Hello
Have you read https://github.com/jstakun/elastalert-ocp/blob/master/README.md ?
From OCP 4.5 you need to use bearer token for authenication

**Comment by ghost** [comment]
Thanks for your reply!

Yes, I also tried retrieving the token via oc sa get-token elastalert command as stated in the README.md file and defined it in the configmap for es_bearer parameter, but it doesn't seem to have any difference in the elastalert pods logs, even deleting the pod let it to be recreated, it fails with the exact same ERROR log.

**Comment by jstakun** [comment]
Have you also configured each Elasticsearch pod as described in Readme?
What OpenShift version are you running?

**Comment by ghost** [comment]
I am using Openshift v4.6, here some more information

```
 ./oc version
Client Version: 4.6.38
Server Version: 4.6.38
Kubernetes Version: v1.19.0+b00ba52
 
 #oc get csv --namespace service-telemetry
NAME                                         DISPLAY                                         VERSION          REPLACES                                     PHASE
amq7-cert-manager.v1.0.0                     Red Hat Integration - AMQ Certificate Manager   1.0.0                                                         Succeeded
amq7-interconnect-operator.v1.10.4           Red Hat Integration - AMQ Interconnect          1.10.4           amq7-interconnect-operator.v1.10.3           Succeeded
elastic-cloud-eck.v1.7.0                     Elasticsearch (ECK) Operator                    1.7.0            elastic-cloud-eck.v1.6.0                     Succeeded
grafana-operator.v3.10.3                     Grafana Operator                                3.10.3           grafana-operator.v3.10.2                     Succeeded
prometheusoperator.0.47.0                    Prometheus Operator                             0.47.0           prometheusoperator.0.37.0                    Succeeded
service-telemetry-operator.v1.3.1635451892   Service Telemetry Operator                      1.3.1635451892   service-telemetry-operator.v1.3.1632277596   Succeeded
smart-gateway-operator.v3.0.1625839193       Smart Gateway Operator                          3.0.1625839193                                                Succeeded

# ./oc get pods -n service-telemetry
NAME                                                         READY   STATUS    RESTARTS   AGE
alertmanager-default-0                                       2/2     Running   0          144d
default-coll-event-smartgateway-6848fc8774-dx2p5   2/2     Running   0          48d
default-coll-meter-smartgateway-cfd88d6ff-59xj8    2/2     Running   1          48d
default-x-coll-event-smartgateway-7c5d9c6db5-qk8c4   2/2     Running   4          144d
default-x-coll-meter-smartgateway-64bd4bb7fc-zh7fv   2/2     Running   2          145d
default-interconnect-668d5bbcd6-vwlxl                        1/1     Running   0          145d
elastic-operator-67c8545479-jrprq                            1/1     Running   0          114d
elasticsearch-es-default-0                                   1/1     Running   0          5d14h
grafana-deployment-6cc64cd648-5c447                          1/1     Running   0          69d
grafana-operator-84c484b595-h2v7q                            1/1     Running   0          114d
interconnect-operator-68d5df96f8-2t4j5                       1/1     Running   0          4d20h
kibana-kb-674b5768c6-kvcpc                                   1/1     Running   0          25d
prometheus-default-0                                         2/2     Running   0          144d
prometheus-operator-6b464cdf8-672wc                          1/1     Running   0          145d
service-telemetry-operator-55f7dc6c5b-hslt4                  1/1     Running   0          33d
smart-gateway-operator-546fb9fcd8-lpnhf                      1/1     Running   0          145d
```

I have only one elasticsearch pod in this deployment, when I do oc rsh elasticsearch-pod but I do not have sgconfig directory as you stated in README.md, I have config/role_mapping.yml file but it was empty. I tried configuring also below but it didnt work for my environment, probably this is the missing point in my configuration :

```
   sg_role_admin:
     users:
       - **'CN=system.admin,OU=OpenShift,O=Logging'**
       - 'system:serviceaccount:openshift-elastalert:elastalert'
```
  how should I define the same role mapping below in my configuration (sorry for being a newbie in openshift) this is how's that config directory looks like, how can I define the similar conf above for make this work?
  
```
 ./oc -n service-telemetry rsh elasticsearch-es-default-0 ls -l config/
total 24
-rw-rw----. 1 1000580000 1000580000  199 Dec  7 20:06 elasticsearch.keystore
lrwxrwxrwx. 1 1000580000 root         60 Dec  7 20:06 elasticsearch.yml -> /mnt/elastic-internal/elasticsearch-config/elasticsearch.yml
drwxrwsrwt. 3 root       1000580000  140 Dec  7 20:06 http-certs
-rw-rw----. 1 1000580000 root       2301 Jan 13  2021 jvm.options
drwxrwxr-x. 2 1000580000 root          6 Jan 13  2021 jvm.options.d
-rw-rw----. 1 1000580000 root       8451 Jan 13  2021 log4j2.properties
drwxr-sr-x. 2 1000580000 1000580000   56 Dec  7 20:06 node-transport-cert
-rw-rw----. 1 1000580000 root        578 Dec 10 04:05 role_mapping.yml
lrwxrwxrwx. 1 1000580000 root         48 Dec  7 20:06 roles.yml -> /mnt/elastic-internal/xpack-file-realm/roles.yml
drwxrwsrwt. 3 root       1000580000  140 Dec  7 20:06 transport-certs
drwxrwsrwt. 3 root       1000580000  100 Dec  7 20:06 transport-remote-certs
lrwxrwxrwx. 1 1000580000 root         53 Dec  7 20:06 unicast_hosts.txt -> /mnt/elastic-internal/unicast-hosts/unicast_hosts.txt
lrwxrwxrwx. 1 1000580000 root         44 Dec  7 20:06 users -> /mnt/elastic-internal/xpack-file-realm/users
lrwxrwxrwx. 1 1000580000 root         50 Dec  7 20:06 users_roles -> /mnt/elastic-internal/xpack-file-realm/users_roles
```

Thank you very much for your helps, really appreciated it

**Comment by jstakun** [comment]
This has been tested only with elasticsearch pods deployed by OpenShift ElasticSearch Operator as part of OpenShift Logging setup. These pods contains file roles_mapping.yml in /opt/app-root/src/sgconfig. 
I guess you have deployed Elasticsearch pod using Elasticsearch (ECK) Operator from Elastic. If that's the case you need to ask Elastic how to grant admin perimission to elastalert service account so that it can interact your Elasticsearch pod.

**Comment by ghost** [comment]
@jstakun thank you for the precious insights that's exactly what's happening, I will follow up from here. closing the issue
